### ISSUE TITLE
module imports

### ISSUE THREAD

**Issue by Silas-Asamoah** [buabaj/fastML#4]
**Is your feature request related to a problem? Please describe.**
The module imports within the fastML function will cause calls to the function to take longer which reduces efficiency and it's not necessary since it's only one source file.

**Describe the solution you'd like**
Putting the imports at the top of the function because it is a small cost that is paid once and easy for dependency tracking.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by buabaj** [comment]
good thinking

**Comment by buabaj** [comment]
did you test your changes?

**Comment by Silas-Asamoah** [comment]
#5
