### ISSUE TITLE
Separate functions to handle individual algorithms

### ISSUE THREAD

**Issue by buabaj** [buabaj/fastML#8]
1. 

**Is your feature request related to a problem? Please describe.**
Write separate functions for every individual algorithm instead of throwing everything up into one big function. By doing this, we call  indivudual algorithms we only need and not everything in general. this also helps in futher implementing advanced features of particular algorithms.

**Comment by Silas-Asamoah** [comment]
How do you plan on writing that?
I'm thinking it would be redundant to breakdown the classification algorithms into different functions with the accompanying metrics. Meaning for every algorithm you want to use you have to make a call to every single attribute you want which is almost the same as making calls using sklearn. That's my opinion though, Im interested in your take

**Comment by buabaj** [comment]
you make a good point. i'll take that out for now till there's a need for that
